name: revcl-AzureVmwareSolutionVmWorkloadsBackupPolicy
title: Ensure you have a documented and implemented backup policy and solution for
  Azure VMware Solution VM workloads
source:
  type: revcl
  file: ./checklists/waf_checklist.en.json
resourceTypes:
- microsoft.avs/privateclouds
waf: Operations
severity: 1
labels:
  guid: 589d457a-927c-4397-9d11-02cad6aae11e
links: []
queries: {}
schemaVersion: 1
id: 589d457a-927c-4397-9d11-02cad6aae11e
services: []
automation:
  status: unknown
  validatedAt: null
provenance:
  upstreamRevision: null
  lastReviewed: null
  sources: []
