---
name: Lint v2 recommendations and checklists
on:
  push:
    branches: [v2, v3]
  pull_request:
    branches: [v2, v3]

permissions:
  contents: read

jobs:
  build:
    name: Lint v2 recommendations and checklists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Check unique names and schema conformity
        id: checklistlint
        uses: ./.github/actions/recov2lint
        with:
          folder: './v2'
          verbose: 'false'
